### ISSUE TITLE
ssh-helper#write's appending process can result in duplicate keys in `id_rsa`

### ISSUE THREAD

**Issue by drewkit** [codeship-library/docker-utilities#6]
- [follow steps in demo project](https://github.com/drewkitch/setting-ssh-private-key-in-pro)
- run `jet steps` multiple times
- cat `id_rsa` file
- note duplicates of private key

Might have undesirable side effects for ssh related steps run from local `jet`?

**Comment by mlocher** [comment]
I'm not aware that duplicate entries in an `authorized_keys` file are an issue. Did we get a ticket on this topic? 

We can certainly check for the existence of the key, but since it makes the script a bit more complicated, is not required for the automated builds and (afaik) doesn't impact local builds I'd prefer not doing this atm.

**Comment by drewkit** [comment]
We did not get a ticket on the topic and I'm not actually certain that it will cause issues for users (certainly won't in Codeship Pro build). Will close issue for now, thanks.
